# Generated by Django 3.2.6 on 2021-08-29 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_payment', models.CharField(blank=True, max_length=45, null=True)),
                ('full_name', models.CharField(max_length=45, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('grade', models.CharField(choices=[('Nursery', 'Nursery'), ('Pre', 'Pre'), ('KSA', 'KSA'), ('KSB', 'KSB'), ('KSC', 'KSC')], max_length=20, null=True)),
                ('residence', models.CharField(choices=[('Adamsu', 'Adamsu'), ('Mpuasu', 'Mpuasu'), ('Bodaa', 'Bodaa'), ('Kofitia', 'Kofitia'), ('Adiokor1', 'Adiokor1'), ('Adiokor2', 'Adiokor2'), ('Zezera', 'Zezera')], max_length=45, null=True)),
                ('name_of_mother', models.CharField(max_length=45, null=True)),
                ('name_of_father', models.CharField(max_length=45, null=True)),
                ('parents_contact', models.CharField(max_length=10, null=True)),
                ('amount_to_pay', models.FloatField(null=True)),
                ('how_many_books_to_buy', models.CharField(choices=[('one', 'one'), ('four', 'four')], max_length=10, null=True)),
                ('completed_paying_books', models.BooleanField(default=False)),
                ('troll', models.BooleanField(default=False)),
                ('soap', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_payment', models.CharField(blank=True, max_length=45, null=True)),
                ('make_payment', models.FloatField(blank=True, null=True)),
                ('book_payment', models.FloatField(blank=True, null=True)),
                ('when_made', models.DateField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.student')),
            ],
        ),
    ]
