# Generated by Django 3.2.6 on 2021-08-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='website_payment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='website_payment',
        ),
    ]
